/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.frontEnd;

import bancos.Conexao;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ana
 */


public class frontEnd extends javax.swing.JFrame {

    /**
     * Creates new form frontEnd
     */
    
    int user=0; 
    
    public frontEnd() {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frontEnd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frontEnd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frontEnd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frontEnd.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        ConfTela();
    }
    
    public void runSplash()
    {
        new Thread(){
           
            public void run ()
            {
               
                for(int i = 0; i<101; i+=2){
                    try 
                    {
                        jProgressBar1.setValue(i);
                       
                        if(jProgressBar1.getValue() <= 40){
                            jLabel55.setText("Carregando arquivos...");
 
                        }else if(jProgressBar1.getValue() <=65){
                            jLabel55.setText("Montando interface...");
                        }else if (jProgressBar1.getValue()<=80){
                            jLabel55.setText("Quase pronto...");
                        }
                        else if (jProgressBar1.getValue() == 100){
                            sleep(20);
                            
                            CardLayout cl = (CardLayout) Projeto.getLayout();
                            cl.show(Projeto, "Interno");
                            //this.SetVisible(true);

                            CardLayout cls = (CardLayout) Principal.getLayout();
                            cls.show(Principal, "Inicial");
                            //this.setVisible(true);
                            comboBusca.setVisible(false);
                            comboBusca.setEnabled(false);
                            
                        }
                            
                        sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(frontEnd.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   
                }
            }
           
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Projeto = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JPasswordField();
        Interno = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        Info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        comboBusca = new javax.swing.JComboBox<>();
        Principal = new javax.swing.JPanel();
        Inicial = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Busca = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        Detalhes = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Voto = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        Cadastro = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JPasswordField();
        SplashScreen = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel55 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Projeto"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Projeto.setPreferredSize(new java.awt.Dimension(1002, 580));
        Projeto.setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setToolTipText("Digite seu usuário");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/logo.png"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/entrar.png"))); // NOI18N
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(19, 175, 189));
        jLabel30.setText("Cadastre-se");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(183, 180, 180));
        jLabel33.setText("Ainda não é cadastrado?");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextField2.setToolTipText("Digite sua senha");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel31)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30))
                            .addComponent(jTextField2))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        Projeto.add(Login, "Login");

        Interno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(238, 238, 238));
        Menu.setPreferredSize(new java.awt.Dimension(151, 400));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 158, 171));
        jLabel3.setText("Inicial");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(150, 147, 147));
        jLabel4.setText("Docente");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(150, 147, 147));
        jLabel5.setText("Restaurante");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(150, 147, 147));
        jLabel6.setText("Sala");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(150, 147, 147));
        jLabel7.setText("Curso");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(150, 147, 147));
        jLabel8.setText("Biblioteca");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(150, 147, 147));
        jLabel53.setText("Laboratório");
        jLabel53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel53)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        Interno.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 410));

        Info.setBackground(new java.awt.Color(13, 158, 171));
        Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do Usuário");
        jLabel1.setToolTipText("Perfil");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Info.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/logo_sem_fundo.png"))); // NOI18N
        Info.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 164, 124));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Texto com a descrição do campus");
        Info.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 280, 30));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/busca_campus.png"))); // NOI18N
        jLabel49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        Info.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 40));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/power.png"))); // NOI18N
        jLabel50.setToolTipText("Sair");
        jLabel50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        Info.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));
        Info.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 100, 100));
        Info.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 120, 90));

        comboBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        comboBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboBuscaFocusLost(evt);
            }
        });
        comboBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscaActionPerformed(evt);
            }
        });
        Info.add(comboBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 160, 40));

        Interno.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 170));

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setLayout(new java.awt.CardLayout());

        Inicial.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/estrutura.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/docentes.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/biblioteca.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/salas.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(183, 180, 180));
        jLabel9.setText("Melhor Professor");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(183, 180, 180));
        jLabel20.setText("Média da Biblioteca");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(183, 180, 180));
        jLabel22.setText("Melhor Estrutura");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(183, 180, 180));
        jLabel23.setText("Média da Sala");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(13, 158, 171));
        jLabel24.setText("RESULTADO");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(13, 158, 171));
        jLabel25.setText("RESULTADO");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(13, 158, 171));
        jLabel26.setText("RESULTADO");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(13, 158, 171));
        jLabel27.setText("RESULTADO");

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/resultado.png"))); // NOI18N

        javax.swing.GroupLayout InicialLayout = new javax.swing.GroupLayout(Inicial);
        Inicial.setLayout(InicialLayout);
        InicialLayout.setHorizontalGroup(
            InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicialLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)))
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel26)))
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel27)))
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel25))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(48, 48, 48))
        );
        InicialLayout.setVerticalGroup(
            InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicialLayout.createSequentialGroup()
                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel18))
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addGap(26, 26, 26)
                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)))
                .addGap(32, 32, 32)
                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)))
                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicialLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InicialLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        Principal.add(Inicial, "Inicial");

        Busca.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Busca");

        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Breve descrição sobre o item");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(13, 158, 171));
        jLabel28.setText("Título do item");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(13, 158, 171));
        jLabel37.setText("Título do item");
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        jLabel40.setForeground(new java.awt.Color(153, 153, 153));
        jLabel40.setText("Breve descrição sobre o item");

        jLabel41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(13, 158, 171));
        jLabel41.setText("Título do item");
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });

        jLabel42.setForeground(new java.awt.Color(153, 153, 153));
        jLabel42.setText("Breve descrição sobre o item");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(13, 158, 171));
        jLabel43.setText("Título do item");
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });

        jLabel44.setForeground(new java.awt.Color(153, 153, 153));
        jLabel44.setText("Breve descrição sobre o item");

        javax.swing.GroupLayout BuscaLayout = new javax.swing.GroupLayout(Busca);
        Busca.setLayout(BuscaLayout);
        BuscaLayout.setHorizontalGroup(
            BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel12)
                    .addComponent(jLabel37)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addContainerGap(660, Short.MAX_VALUE))
        );
        BuscaLayout.setVerticalGroup(
            BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        Principal.add(Busca, "Busca");

        Detalhes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("| Detalhes");

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Busca");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/resultado.png"))); // NOI18N

        jLabel46.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(19, 175, 189));
        jLabel46.setText("Título do item");

        jLabel47.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(153, 153, 153));
        jLabel47.setText("<html>Aqui vem uma breve descrição sobre o item que foi selecionado.</html>");

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/votar.png"))); // NOI18N
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DetalhesLayout = new javax.swing.GroupLayout(Detalhes);
        Detalhes.setLayout(DetalhesLayout);
        DetalhesLayout.setHorizontalGroup(
            DetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetalhesLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(DetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetalhesLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addGap(26, 26, 26)
                .addComponent(jLabel45)
                .addGap(47, 47, 47))
        );
        DetalhesLayout.setVerticalGroup(
            DetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetalhesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGroup(DetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetalhesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DetalhesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Principal.add(Detalhes, "Detalhes");

        Voto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel51.setForeground(new java.awt.Color(153, 153, 153));
        jLabel51.setText("Busca");
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });

        jLabel52.setForeground(new java.awt.Color(153, 153, 153));
        jLabel52.setText("| Detalhes");
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(19, 175, 189));
        jLabel54.setText("Título do item");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton1.setText("Bom");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton2.setText("Regular");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton3.setText("Ruim");

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton4.setText("Péssimo");

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton5.setText("Ótimo");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/votar.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VotoLayout = new javax.swing.GroupLayout(Voto);
        Voto.setLayout(VotoLayout);
        VotoLayout.setHorizontalGroup(
            VotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VotoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(VotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VotoLayout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(433, Short.MAX_VALUE))
        );
        VotoLayout.setVerticalGroup(
            VotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        Principal.add(Voto, "Voto");

        Interno.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 850, 410));

        Projeto.add(Interno, "Interno");

        Cadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(3, 159, 175));
        jLabel34.setText("Cadastro");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/logo_mini.png"))); // NOI18N

        jTextField4.setToolTipText("Digite seu E-mail");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setToolTipText("Digite seu nome");
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("<html>\nCaso você seja aluno de algum campus, entre em contato com a secretária responsável para receber seu usuário e senha.\n<br/>\n<br/>\nPara os que não são alunos, basta informar os dados ao lado para ter acesso ao sistema. <br/><br/>\n<b>Lembre-se:</b> não alunos tem permissão apenas de visualização, ou seja, não pode votar.\n\n</html>"); // NOI18N
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel35.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 153, 255));
        jLabel38.setText("CANCELAR");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/salvar.png"))); // NOI18N
        jLabel39.setText("jLabel39");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        jTextField3.setToolTipText("Digite sua senha");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout CadastroLayout = new javax.swing.GroupLayout(Cadastro);
        Cadastro.setLayout(CadastroLayout);
        CadastroLayout.setHorizontalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CadastroLayout.createSequentialGroup()
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CadastroLayout.createSequentialGroup()
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addComponent(jTextField3)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        CadastroLayout.setVerticalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel36)))
                .addGap(71, 71, 71)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3)))
                .addGap(35, 35, 35)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        Projeto.add(Cadastro, "Cadastro");

        SplashScreen.setBackground(new java.awt.Color(255, 255, 255));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/frontEnd/imagens/logo.png"))); // NOI18N

        jProgressBar1.setForeground(new java.awt.Color(0, 45, 97));
        jProgressBar1.setStringPainted(true);

        jLabel55.setText("Teste");

        javax.swing.GroupLayout SplashScreenLayout = new javax.swing.GroupLayout(SplashScreen);
        SplashScreen.setLayout(SplashScreenLayout);
        SplashScreenLayout.setHorizontalGroup(
            SplashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashScreenLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel56)
                .addGap(36, 36, 36)
                .addGroup(SplashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SplashScreenLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel55)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        SplashScreenLayout.setVerticalGroup(
            SplashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashScreenLayout.createSequentialGroup()
                .addGroup(SplashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SplashScreenLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel56))
                    .addGroup(SplashScreenLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        Projeto.add(SplashScreen, "SplashScreen");

        getContentPane().add(Projeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ConfTela(){
        
        //Configura a altura e largura da tela de login e nao deixa ela aumentar de tamanho
        //this.setSize(376, 525);
	this.setResizable(false);
        
        //centraliza o jframe de login
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        //esconde a msg de erro de login
        //errologin.setVisible(false);
        
    }
    
    
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Busca");
        this.setVisible(true);  
        
        String teste = jLabel4.getText();        
        jLabel11.setText(teste);
        jLabel13.setText(teste);
        jLabel51.setText(teste);
        
        // todo o menu fica na cor cinza
        jLabel3.setForeground(Color.decode("#969393")); // inicial
        jLabel5.setForeground(Color.decode("#969393")); // restaurante
        jLabel6.setForeground(Color.decode("#969393")); // sala
        jLabel7.setForeground(Color.decode("#969393")); // curso
        jLabel8.setForeground(Color.decode("#969393")); // biblioteca
        jLabel53.setForeground(Color.decode("#969393")); // laboratorio
        
        // ativa a cor em "Docente"
        jLabel4.setForeground(Color.decode("#0D9EAB")); // docente
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Inicial");
        this.setVisible(true);
        
        String teste = jLabel3.getText();        
        jLabel11.setText(teste);
        jLabel13.setText(teste);
        jLabel51.setText(teste);
        
        jLabel4.setForeground(Color.decode("#969393")); // docente
        jLabel5.setForeground(Color.decode("#969393")); // restaurante
        jLabel6.setForeground(Color.decode("#969393")); // sala
        jLabel7.setForeground(Color.decode("#969393")); // curso
        jLabel8.setForeground(Color.decode("#969393")); // biblioteca
        jLabel53.setForeground(Color.decode("#969393")); // laboratorio
        
        // ativa a cor em "Inicial"
        jLabel3.setForeground(Color.decode("#0D9EAB")); // inicial
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Busca");
        this.setVisible(true);
        
        String teste = jLabel8.getText();        
        jLabel11.setText(teste);
        jLabel13.setText(teste);
        jLabel51.setText(teste);
        
        jLabel3.setForeground(Color.decode("#969393")); // inicial
        jLabel5.setForeground(Color.decode("#969393")); // restaurante
        jLabel6.setForeground(Color.decode("#969393")); // sala
        jLabel7.setForeground(Color.decode("#969393")); // curso
        jLabel4.setForeground(Color.decode("#969393")); // docente
        jLabel53.setForeground(Color.decode("#969393")); // laboratorio
        
        // ativa a cor em "Biblioteca"
        jLabel8.setForeground(Color.decode("#0D9EAB")); // biblioteca
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Busca");
        this.setVisible(true);
        
        String teste = jLabel5.getText();        
        jLabel11.setText(teste);
        jLabel13.setText(teste);
        jLabel51.setText(teste);
        
        jLabel3.setForeground(Color.decode("#969393")); // inicial
        jLabel4.setForeground(Color.decode("#969393")); // docente
        jLabel6.setForeground(Color.decode("#969393")); // sala
        jLabel7.setForeground(Color.decode("#969393")); // curso
        jLabel8.setForeground(Color.decode("#969393")); // biblioteca
        jLabel53.setForeground(Color.decode("#969393")); // laboratorio
        
        // ativa a cor em "Restaurante"
        jLabel5.setForeground(Color.decode("#0D9EAB")); // restaurante
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Busca");
        this.setVisible(true);
        
        String teste = jLabel6.getText();        
        jLabel11.setText(teste);
        jLabel13.setText(teste);
        jLabel51.setText(teste);
        
        jLabel3.setForeground(Color.decode("#969393")); // inicial
        jLabel5.setForeground(Color.decode("#969393")); // restaurante
        jLabel4.setForeground(Color.decode("#969393")); // docente
        jLabel7.setForeground(Color.decode("#969393")); // curso
        jLabel8.setForeground(Color.decode("#969393")); // biblioteca
        jLabel53.setForeground(Color.decode("#969393")); // laboratorio
        
        // ativa a cor em "Sala"
        jLabel6.setForeground(Color.decode("#0D9EAB")); // sala
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Busca");
        this.setVisible(true);
        
        String teste = jLabel7.getText();        
        jLabel11.setText(teste);
        jLabel13.setText(teste);
        jLabel51.setText(teste);
        
        jLabel3.setForeground(Color.decode("#969393")); // inicial
        jLabel5.setForeground(Color.decode("#969393")); // restaurante
        jLabel6.setForeground(Color.decode("#969393")); // sala
        jLabel4.setForeground(Color.decode("#969393")); // docente
        jLabel8.setForeground(Color.decode("#969393")); // biblioteca
        jLabel53.setForeground(Color.decode("#969393")); // laboratorio
        
        // ativa a cor em "Curso"
        jLabel7.setForeground(Color.decode("#0D9EAB")); // curso
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Detalhes");
        this.setVisible(true);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Busca");
        this.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        
        
        
        try{
            Conexao conec = new Conexao();
            conec.getConexaoMySQL();
        
            String sql2 = "Select idusuario, login, senha, campususu, nome from usuario";
            Statement stm2 = conec.getConexao().createStatement();
            
            ResultSet RS2 = stm2.executeQuery(sql2);
            
            int resposta = 1;
            
            char[] senhadigitada = jTextField2.getPassword();
            String senhacomparada = "";
            
            int k;
            
            for(k = 0; k < senhadigitada.length; k++){
                senhacomparada += senhadigitada[k];
            }
            if(RS2 == null){
                JOptionPane.showMessageDialog(null, "Dados Incorretos!");
            }
            while(RS2.next()){
                if((jTextField1.getText().equals(RS2.getString(2))) && (senhacomparada.equals(RS2.getString(3)))){
                    user= Integer.parseInt(RS2.getString(1));
                    int campusUsu=0;
                    campusUsu = Integer.parseInt(RS2.getString(4));
                    CardLayout spl = (CardLayout) Projeto.getLayout();
                    
                    
                    
                    jLabel1.setText(RS2.getString(5));
                    conec.getConexaoMySQL(); 
                    String sql3 = "Select logocampus, logouniversidade, descricao from campus where idcampus="+campusUsu;
                    
             
            Statement stm3 = conec.getConexao().createStatement();
            
            ResultSet RS3 = stm3.executeQuery(sql3);
            
            if(RS3 == null){
                JOptionPane.showMessageDialog(null, "Dados sobre o campus não encontrado!");
            }
            while(RS3.next()){
            jLabel16.setText(RS3.getString(3));
            
            if(RS3.getBlob("logocampus") != null){
                Blob logoCampus = RS3.getBlob("logocampus");
                int tamanhoimagemCampus = (int) logoCampus.length(); //Icone é meu blob
                byte[] bytesCampus  = logoCampus.getBytes(1, tamanhoimagemCampus); //Transforma em bytes
                ImageIcon iconCampus = new ImageIcon(bytesCampus ); //Remonta como Icone
        
                Image imgCampus = iconCampus.getImage() ;  //Remonta como Imagem
                Image newimgCampus = imgCampus.getScaledInstance( 132, 132,  java.awt.Image.SCALE_SMOOTH ) ;   //Redimensiona
                iconCampus = new ImageIcon( newimgCampus ); //Remonta como Icone
        
                jLabel58.setIcon(iconCampus); //Define o Label como Imagem
            }
            
            if(RS3.getBlob("logouniversidade") != null){
                Blob logoUniversidade = RS3.getBlob("logouniversidade");
                int tamanhoimagemUniversidade = (int) logoUniversidade.length(); //Icone é meu blob
                byte[] bytesUniversidade = logoUniversidade.getBytes(1, tamanhoimagemUniversidade); //Transforma em bytes
                ImageIcon iconUniversidade = new ImageIcon(bytesUniversidade); //Remonta como Icone
        
                Image imgUniversidade = iconUniversidade.getImage() ;  //Remonta como Imagem
                Image newimgUniversidade = imgUniversidade.getScaledInstance( 132, 132,  java.awt.Image.SCALE_SMOOTH ) ;   //Redimensiona
                iconUniversidade = new ImageIcon( newimgUniversidade ); //Remonta como Icone
        
                jLabel57.setIcon(iconUniversidade); //Define o Label como Imagem
            
            }
            
            }
             spl.show(Projeto,"SplashScreen");
                    
                    this.setVisible(true);
                   
                    runSplash();//Abre o SplashScreen
                    
                    resposta = 0;
                }
                
            }
            
            if(resposta == 1){
                JOptionPane.showMessageDialog(null, "Dados Incorretos!");
            }
        }
        catch(SQLException e){
            System.out.println(e);
        }
        
        //teste
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Projeto.getLayout();
        cl.show(Projeto, "Cadastro");
        this.setVisible(true);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
        
        String cadastronomeusuario = jTextField5.getText();
        String cadastroemail = jTextField4.getText();
        String cadastrosenha = "";
        
        char[] pegasenha = jTextField3.getPassword();
        int i;
        
        for(i = 0; i < pegasenha.length; i++){
            cadastrosenha += pegasenha[i];
        }
        
        if((cadastronomeusuario != "") && (cadastroemail != "") && (cadastrosenha != "")){
            String cadastrorequisicao = "INSERT INTO `usuario` (`idusuario`,`nome`, `login`, `senha`, `email`, `tipousuario`, `campususu`) VALUES (DEFAULT, '" + cadastronomeusuario + "', '" + cadastroemail + "', '" + cadastrosenha + "', '" + cadastroemail + "', 1, 1);";
        
            try{
                Conexao conec = new Conexao();
                conec.getConexaoMySQL();
                Statement stm1 = conec.getConexao().createStatement();

                int RS1 = stm1.executeUpdate(cadastrorequisicao);
                
                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!");
                CardLayout cl = (CardLayout) Projeto.getLayout();
                cl.show(Projeto, "Login");
                this.setVisible(true);
            }
            catch(SQLException e){
                System.out.println(e);            
            }
        }
        else{
            jTextField5.setText("");
            jTextField4.setText("");
            jTextField3.setText("");
            JOptionPane.showMessageDialog(null, "Dados Inválidos!");
        }
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Projeto.getLayout();
        cl.show(Projeto, "Login");
        this.setVisible(true);
        
        comboBusca.setVisible(false);
        comboBusca.setEnabled(false);
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Projeto.getLayout();
        cl.show(Projeto, "Login");
        this.setVisible(true);
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Voto");
        this.setVisible(true);
    }//GEN-LAST:event_jLabel48MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Detalhes");
        this.setVisible(true);
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Detalhes");
        this.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "Busca");
        this.setVisible(true);
        
        String teste = jLabel53.getText();        
        jLabel11.setText(teste);
        jLabel13.setText(teste);
        jLabel51.setText(teste);
        
        jLabel3.setForeground(Color.decode("#969393")); // inicial
        jLabel5.setForeground(Color.decode("#969393")); // restaurante
        jLabel4.setForeground(Color.decode("#969393")); // docente
        jLabel7.setForeground(Color.decode("#969393")); // curso
        jLabel8.setForeground(Color.decode("#969393")); // biblioteca
        jLabel6.setForeground(Color.decode("#969393")); // sala
        
        // ativa a cor em "Sala"
        jLabel53.setForeground(Color.decode("#0D9EAB")); // laboratorio
    }//GEN-LAST:event_jLabel53MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        comboBusca.setVisible(true);
        comboBusca.setEnabled(true);
        
        Conexao conec = new Conexao(); // INSTANCIA UM OBJETO DA CLASSSE Conexao
        conec.getConexaoMySQL();       // REALIZA O MÉTODO DE CONEXÃO COM O BANCO

	String sql3 = "Select nomecampus from campus"; // OPERAÇÃO SQL DESEJADA
        
        try{
            Statement stm3 = conec.getConexao().createStatement(); // REALIZA A OPERAÇÃO SQL - STATEMENT - PELO JAVA
            ResultSet RS3 = stm3.executeQuery(sql3); // REUNE TODAS AS LINHAS RESULTANTES DA OPERAÇÃO
            
            //ArrayList lista = new ArrayList();
            
            int c2 = 0, numlinhas = 0;
            

            while(RS3.next()){
                numlinhas++;                
            }
            
            while(RS3.previous()){                
            }
            
            Object[] campus = new Object[numlinhas];
            
            if(comboBusca.getItemCount() > 1){
                
            }
            else{
                while(RS3.next()){
                campus[c2] = RS3.getObject(1);
                c2++;
                comboBusca.addItem(RS3.getString(1));
                //JOptionPane.showMessageDialog(null, "Ta foda");
                }
            }
            
            //comboBusca.addItem(campus);
            
            
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel49MouseClicked

    private void comboBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBuscaFocusLost
        comboBusca.setEnabled(false);
        comboBusca.setVisible(false);
    }//GEN-LAST:event_comboBuscaFocusLost

    private void comboBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscaActionPerformed
        if(comboBusca.getSelectedItem() == ""){
            comboBusca.setEnabled(false);
            comboBusca.setVisible(false);
        }
    }//GEN-LAST:event_comboBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frontEnd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Busca;
    private javax.swing.JPanel Cadastro;
    private javax.swing.JPanel Detalhes;
    private javax.swing.JPanel Info;
    private javax.swing.JPanel Inicial;
    private javax.swing.JPanel Interno;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel Projeto;
    private javax.swing.JPanel SplashScreen;
    private javax.swing.JPanel Voto;
    private javax.swing.JComboBox<String> comboBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    private javax.swing.JPasswordField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
